const eventsData = [
  {
    id: '1',
    title: 'Soirée de bienvenue BDE',
    description: 'La soirée de bienvenue organisée par le BDE pour accueillir les nouveaux étudiants. Venez nombreux ! Boissons et snacks offerts.',
    creator: 'BDE Université',
    location: 'Amphi A - Bâtiment principal',
    locationLat: 48.6921,
    locationLng: 6.1844,
    contactInfo: 'bde@universite.fr | 03 83 XX XX XX',
    association: 'BDE',
    type: 'Soirée',
    startDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
    imageUrl: null,
  },
  {
    id: '2',
    title: 'Tournoi de foot inter-associations',
    description: 'Grand tournoi de football entre les associations de l\'université. Inscriptions ouvertes jusqu\'au 30 avril. Trophée et lots à gagner !',
    creator: 'Association Sportive',
    location: 'Stade universitaire',
    locationLat: 48.6950,
    locationLng: 6.1820,
    contactInfo: 'sport@universite.fr',
    association: 'AS Université',
    type: 'Sport',
    startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000).toISOString(),
    imageUrl: null,
  },
  {
    id: '3',
    title: 'Conférence IA & Société',
    description: 'Conférence sur l\'impact de l\'intelligence artificielle dans notre société, animée par des chercheurs et professionnels du domaine.',
    creator: 'Laboratoire LORIA',
    location: 'Salle des conférences - Bâtiment Sciences',
    locationLat: 48.6935,
    locationLng: 6.1860,
    contactInfo: 'loria@universite.fr | www.loria.fr',
    association: null,
    type: 'Conférence',
    startDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    imageUrl: null,
  },
  {
    id: '4',
    title: 'Vente de crêpes humanitaire',
    description: 'Vente de crêpes au profit d\'une association humanitaire. Venez soutenir une bonne cause tout en vous régalant !',
    creator: 'Étudiants Solidaires',
    location: 'Hall d\'entrée - Bâtiment A',
    locationLat: 48.6915,
    locationLng: 6.1838,
    contactInfo: 'solidaires@universite.fr',
    association: 'Étudiants Solidaires',
    type: 'Vente',
    startDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
    imageUrl: null,
  },
  {
    id: '5',
    title: 'Hackathon 24h',
    description: 'Hackathon de 24h ouvert à tous les étudiants. Formez des équipes de 3 à 5 personnes et relevez des défis technologiques. Prix à gagner !',
    creator: 'Club Informatique',
    location: 'Salle informatique - Bâtiment IUT',
    locationLat: 48.6900,
    locationLng: 6.1870,
    contactInfo: 'info-club@universite.fr',
    association: 'Club Informatique',
    type: 'Hackathon',
    startDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: null,
  },
];

module.exports = { eventsData };
